// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // 1. Ubicacion de las tablas
  schema: "prisma/schema.prisma",
  
  // 2. Indicar donde guardar los cambios de sql
  migrations: {
    path: "prisma/migrations",
  },
  
  // 3. Inyecta la conexión segura de PostgreSQL desde el archivo .env
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});